name: domaincolorex
channels:
  - conda-forge
dependencies:
  - python=3.9.2   # or 2.7
  - pip
  - pip:
    - cplot
  - mypy
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  - ipywidgets
  - ipympl
  - matplotlib
  - numpy
  - lenses
  - toolz
